USE BRILLICA;
SHOW TABLES;
SELECT * FROM INFO;
TRUNCATE INFO;           # DELETES ENTIRE DATA LEAVING COLUMN HEADERS
SELECT * FROM INFO;   
DROP TABLE INFO;         # DELETES TABLE FROM DATABASE
SELECT * FROM EMP;
# ADDING A COLUMN IN TABLE AS BONUS
ALTER TABLE EMP ADD COLUMN BONUS FLOAT;
SELECT * FROM EMP;
# ADD A COLUMN OF STATUS IN LAST OF TABLE.
ALTER TABLE EMP ADD COLUMN STATUS TEXT;
# ADD COLUMN OF MONTH_NAME AFTER HIRE_DATE.
ALTER TABLE EMP ADD COLUMN MONTH_NAME TEXT AFTER HIRE_DATE;
# ADD COLUMN OF GENDER BEFORE DEPARTMENT.
ALTER TABLE EMP ADD COLUMN GENDER TEXT AFTER NAME;
# ADD A COLUMN OF EMP_CODE AT STARTING OF TABLE.
ALTER TABLE EMP ADD COLUMN CODE INT FIRST;
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# HOW TO DELETE COLUMNS FROM TABLE.
SELECT * FROM EMP;
ALTER TABLE EMP DROP COLUMN STATUS;
ALTER TABLE EMP DROP COLUMN EMP_CODE;
ALTER TABLE EMP DROP COLUMN GENDER;
ALTER TABLE EMP DROP COLUMN MONTH_NAME;
ALTER TABLE EMP DROP COLUMN BONUS;
ALTER TABLE EMP DROP COLUMN CODE;
SELECT * FROM EMP;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# HOW TO CHECK THE DATA TYPE OF COLUMN.
DESC EMP;
DESCRIBE EMP;
# HOW TO CHANGE THE DATA TYPE OF COLUMNS.
ALTER TABLE EMP MODIFY SALARY TEXT;
-----------------------------------------------------# HOW TO RENAME THE COLUMN HEADERS #-----------------------------------------------------------------------------------
ALTER TABLE EMP RENAME COLUMN DEPARTMENT TO DEPT;
ALTER TABLE EMP RENAME COLUMN HIRE_DATE TO DOJ; 
-----------------------------------------------------# HOW TO RENAME THE TABLE #-------------------------------------------------------------------------------------------
ALTER TABLE EMP RENAME EMP2;
RENAME TABLE EMP2 TO EMP;
SELECT * FROM EMP2;
ALTER TABLE EMP2 RENAME COLUMN NAME TO EMP_NAME, RENAME COLUMN DEPT TO DEPARTMENT, RENAME COLUMN DOJ TO HIRE_DATE;
SELECT * FROM EMP2;
# BEFORE USING THE UPDATE AND DELETE COMMANDWE USE:
SET SQL_SAFE_UPDATES=0;
# It is a kind of security which does not allow to delete original data from the table. 0 means off and 1 means on.
SELECT * FROM EMP2;
# WRITE A QUERY TO DELETE ALL ROWS WHOSE NAME STARTSWITH "J".
DELETE FROM EMP2 WHERE LEFT(TRIM(EMP_NAME),1)="J";
SELECT * FROM EMP2 WHERE LEFT(TRIM(EMP_NAME),1)="J";
# DELETE THE EMPLOYEE DETAILS WITH THE MAX SALARY.
DELETE FROM EMP2 ORDER BY SALARY DESC LIMIT 1;
SELECT * FROM EMP2;
-- DELETE USED AS TRUNCATE COMMAND TO DELETE THE ENTIRE DATA FROM THE TABLE LEAVING ITS FORMAT IS BY:
DELETE FROM EMP2;
DROP TABLE EMP2;
USE BRILLICA;
SELECT * FROM EMP;
ALTER TABLE EMP DROP COLUMN DESCRIPTION;
SELECT * FROM EMP;
ALTER TABLE EMP RENAME COLUMN DOJ TO HIRE_DATE;
SELECT * FROM EMP;
SET SQL_SAFE_UPDATES=0;
SELECT * FROM EMP;
# ADD VALUE HR AT THE PLACE OF BLANK CELL IN DEPARTMENT.
UPDATE EMP SET DEPARTMENT="HR" WHERE DEPARTMENT="";
SELECT * FROM EMP;
# DELETE ALL DATA ANALYST DEPARTMENT IN DEPARTMENT COLUMN.
UPDATE EMP SET DEPARTMENT="" WHERE DEPARTMENT="DATA ANALYST";
SELECT * FROM EMP;
# DELETE ALL EXTRA SPACE FROM EMP NAME.
UPDATE EMP SET EMP_NAME = TRIM(EMP_NAME);
SELECT * FROM EMP;
UPDATE EMP SET DEPARTMENT="DATA ANALYST" WHERE DEPARTMENT="";
# WRITE A QUERY TO ADD COLUMN STATUS, IF SALARY IS GREATER THAN 50K THEN SHOW HIGH ELSE IF SALARY IS LESS THAN 50K THEN LOW.
ALTER TABLE EMP ADD COLUMN STATUS TEXT;
SELECT * FROM EMP;
UPDATE EMP SET STATUS = "HIGH" WHERE SALARY>50000;
UPDATE EMP SET STATUS ="LOW" WHERE SALARY<=50000;
SELECT * FROM EMP;
# CHANGE THE DEPARTMENT OF DATA ANALYST TO DA WHERE CITY IS PATNA.
UPDATE EMP SET DEPARTMENT = "DA" WHERE DEPARTMENT="DATA ANALYST" AND CITY="PATNA";
SELECT * FROM EMP;
# ADD A COLUMN OF BONUS AND ADD RANDOM NUMBER BETWEEN 1000 TO 5000.
ALTER TABLE EMP ADD COLUMN BONUS INT;
UPDATE EMP SET BONUS = 1000+RAND()*4000;
SELECT * FROM EMP;
ALTER TABLE EMP MODIFY BONUS FLOAT;
UPDATE EMP SET BONUS = ROUND(1000+RAND()*4000,2);
# ADD ACOLUMN OF MONTH_NAME, DAY_NAME AND YEAR AFTER HIRE_DATE AND EXTRACT THESE FROM THE HIRE_DATE COLUMN.
ALTER TABLE EMP ADD COLUMN MONTH_NAME TEXT, ADD COLUMN DAY_NAME TEXT, ADD COLUMN YEAR TEXT;
UPDATE EMP SET MONTH_NAME= monthname(HIRE_DATE);
UPDATE EMP SET DAY_NAME = dayname(HIRE_DATE);
UPDATE EMP SET YEAR = year(HIRE_DATE);
SELECT * FROM EMP;
# DELETE LAST 5 ROWS FROM TABLE.
DELETE FROM EMP ORDER BY `SI NO` DESC LIMIT 5;
SELECT * FROM EMP;
DESC EMP;

