                                                    -- TRIGGERS --
# A TRIGGER IN MYSQL WORKBENCH IS A DATABASE OBJECT THATS ASSOCIATED WITH A TABLE AND IS ACTIVATED WHEN A CERTAIN ACTION IS PERFORMED ON THE TABLE. 
                                                            -- or --
# A trigger is a stored procedure that automatically executes in response to certain events in a specific table or view in a database.  

-- THEY CAN BE USED TO APPLY RESTRICTIONS WHEN ADDING, UPDATING OR REMOVING ROWS. 
-- MAINTAIN REFERENTIAL INTEGRITY RECORD ACTIVITES PERFORMED ON A TABLE. 

CREATE TABLE SALARY(
					EMP_NAME TEXT, 
					SALARY INT);
SELECT * FROM SALARY;

# CREATING A TRIGGER FOR DEDUCTING 500 FROM SALARY :
CREATE TRIGGER T_SALARY
				BEFORE INSERT ON 
                SALARY FOR EACH ROW
                SET NEW.SALARY = NEW.SALARY-@A;

SET @A= 200;
INSERT INTO SALARY VALUES("PRERNA",2000000);
SELECT * FROM SALARY;
SET @A = 2000;
INSERT INTO SALARY VALUES("AMAN",4000);
SELECT * FROM SALARY;

# INDEX : IT IMPROVES DATA RETRIEVING SPEED. 
SELECT * FROM COVID_DATA WHERE CONFIRMED>75000;
CREATE INDEX P ON COVID_DATA(CONFIRMED);
DROP INDEX P ON COVID_DATA;

DELIMITER //
CREATE FUNCTION PRERNA(X TEXT)
	RETURNS TEXT
		DETERMINISTIC
			BEGIN
				RETURN LEFT(TRIM(X),INSTR(TRIM(X)," "));
			END //
DELIMITER ;
SELECT PRERNA(EMP_NAME) AS FIRST_NAME FROM EMPLOYEES;


